// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvftfjespsksensdacnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2ZnRmamVzcHNrc2Vuc2RhY25iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMjIzMjYsImV4cCI6MjA2NTc5ODMyNn0.aGML4YFrQiZCKjWY8fj-bn8mmAg63Z6VYEOO-8--GjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);